apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sheep-dog-dev-mcp-ingress
  labels:
    app: sheep-dog-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /\.well-known
            pathType: ImplementationSpecific
            backend:
              service:
                name: sheep-dog-dev-mcp
                port:
                  number: 80
          - path: /mcp
            pathType: Prefix
            backend:
              service:
                name: sheep-dog-dev-mcp
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sheep-dog-dev-svc-ingress
  labels:
    app: sheep-dog-dev
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sheep-dog-dev-svc
                port:
                  number: 80
